name: Omni-Scrub
description: ""
ports: []
bricks:
- arduino:video_object_detection:
    model: yolox-object-detection
- arduino:web_ui: {}
- arduino:dbstorage_sqlstore: {}
- arduino:dbstorage_tsstore: {}
icon: 🫧
